name: Deploy to staging
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
        default: ${{ github.ref_name }}

env:
  IMAGE_TAG: ${{ inputs.tags }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/dcicentral

jobs:
  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'index.docker.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
