name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_HOST }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build the Docker image
      run: |
        docker build . -t ${{ secrets.ACR_REGISTRY_HOST }}/dcicentral:$(date +%s)
        docker tag ${{ secrets.ACR_REGISTRY_HOST }}/dcicentral:$(date +%s) ${{ secrets.ACR_REGISTRY_HOST }}/dcicentral:latest
        docker push --all-tags ${{ secrets.ACR_REGISTRY_HOST }}/dcicentral
